# Generated by Django 4.1.1 on 2022-12-15 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile_delete_eventuser_alter_event_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
