# Generated by Django 4.1.1 on 2022-12-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_userprofile_options_location_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
    ]
