# Generated by Django 4.1.1 on 2022-12-19 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_event_image_alter_location_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='favorite',
            field=models.BooleanField(default=False),
        ),
    ]
